trussworks/trussels-guide

index.md

Cleaned up the credit cards and added a section about the bubbles.

Minor fixes

---

index.md

Per our discussion at last week's welcoming retro.

Added onboarding survey to second week section

---

index.md

Updated Conferences URL to reflect new policy document.

Updated URL to new Conferences and Professional Development policy

---

distributed.md

Adding Ev's new conclusion

---

distributed.md

Minor copy edits, including fixing spacing errors and typos.

Copy edits to distributed handbook

---

index.md

Adding perks calling out 1Password Families and Tall Poppy. Added to `First 3 months` for lack of a better place to put them.

Adding Perks

---

index.md

Adding information for Habitu8 Trainings.

Habitu8 Addition

---

trussels.md

Make some updates to reflect current practice, and update links to internal docs.

Update guide with new links and updates to discretionary kindness budget

---

distributed.md

Updating the documented backup service we use.

adding backblaze note instead of code 42

---

trussels.md

@jen2000 for your review: Added the [Communication Expectations](https://docs.google.com/document/d/1auMZSl-tUleBpJC8WjG6dtCvaEtjbbbCMnsVR7bIP8c/edit#heading=h.mw7235wtjesw) doc as a resource.

Communication expectations

---

_config.yml

I _think_ this will fix the http/https kerfuffle that happens when I turn on enforce https.

fix css on https site

---

docs/trussels.md

- Bubble prince name updated to Truss Leadership Team
- Updated TLT members 
- Alphabetized TLT members

Updated bubble prince info

---

docs/trussels.md

- Added last names for leadership team to disambiguate from others with same first name
- Changed DM lead from Kayless to Amy
- Updated link to new Staffing worksheet (locked)
- Deleted reference to #wg-offsite2020

Updates to Truss Guide

---

docs/trussels.md
index.md

This PR addresses some confusing language, out-dated info, and fixes some broken or funky links to other documentation up to the "Second Week" section.

Slightly tweaking language and fixing broken links

---

docs/distributed.md

Zoom updated to allow pronouns to be displayed without editing the name. Added a link to show that.

add zoom pronoun instructions link

---

docs/trussels.md

* Corrected typos
* Updated inaccurate / outdated info
* Added clarifying information / context

Reviewed Truss Guide up to First Week

---

docs/trussels.md

- deleted outdated information about internal projects
- deleted outdated information about Press Friendly
- I'm going to be real I don't remember what else I did

Edits to Week 1 onboarding onwards

---

docs/trussels.md

update trussels guide

---

docs/trussels.md

* updated leveling guide from https://docs.google.com/document/d/1AbJBFEkVhSDSRty8oN44PTgiL1NK3X8xe2k4tSpKhhc/edit to https://docs.google.com/document/d/1v_N7IQP6pnm2H1HwWPnddvEV_ZdegynPvV3rGYHE_Sw/edit

update leveling guides

---

docs/trussels.md

removed: 
* Meetings: Manager’s meetings (#puma-wranglers)

removed managers meeting

---

docs/trussels.md

- add link to stakeholders folder

add stakeholders link

---

docs/trussels.md

- updated from #truss-infra to #truss-internal-it-support
- added linked to Retrium TDR

update Retrium instructions

---

docs/trussels.md

- changed all references from #truss-infra to #truss-internal-it-support

update references to #truss-infra

---

docs/trussels.md

Signed-off-by: travelar <erik@truss.works>
Minor updates: 
* Updating Habitu8 information to Arctic Wolf
* Updated list of default channels

Arctic Wolf updates

---

renovate.json

Changes proposed in this pull request:
- Add `renovatebot.json`

Add renovatebot config

---

docs/trussels.md

Changes proposed in this pull request:
- Update Aim2Assist slackbot response based on admin team being in house
- Clean up email footer example
- Other minor formatting

Minor updates to the Trussel's Guide

---

docs/trussels.md

Changes proposed in this pull request:
- Adds clarifying language about 40-hour work week expectation for all Trussels

clarifying 40 hour work week expectation

---

docs/distributed.md

Captions: every Trussel should allow participants to enable captions/transcripts for their meetings, and doing so requires a setting per host.
Hand stack: we've moved away from the chat-based system. Updated language to reflect the use of Zoom's reactions.

Added enabling captions and updated hand stack language

---

docs/trussels.md

Updated names and roles for founders and TLT and added ELT
Changes proposed in this pull request:
- Change 1
- Change 2

Updated Truss Leadership Teams

---

docs/trussels.md

Update trussels.md with content about Truss's approach to O&M work

---

docs/trussels.md

Update trussels.md - fixes typo

---

docs/trussels.md

- Removed duplicated content from public site
- Removed language around a retracted TDR

Updated Diversity section of the Guide
